### ISSUE TITLE
Improve the default chat room title

### ISSUE THREAD

**Issue by carmenlau** [skygear-demo/android-chat-uikit-demo#11]
Current when user create a new chat, the default chat room title is joining the participates but excludes the current user. So when the other user open the conversation, the conversation title will be his name which is strange. 

Update not to exclude the current user.

**Comment by howawong** [comment]
I just verified the chat demo but cannot reproduce the issue. And I think when [creating conversation](https://github.com/skygear-demo/android-chat-uikit-demo/blob/111ceb1d4539b55ff7d83bb5022848bc0efa90f0/app/src/main/java/io/skygear/chatdemo/UsersListActivity.java#L93), the current username is already append.
