### ISSUE TITLE
Update master to use latest chat sdk from git (jitpack)

### ISSUE THREAD

**Issue by carmenlau** [skygear-demo/android-chat-uikit-demo#18]

**Comment by carmenlau** [comment]
The latest branch is using the jitpack already, you can try using the comments. We will have to update some code due to api update. Can you help group the code update in one commit so we can reference easily. Thanks!

**Comment by howawong** [comment]
Yes, i just realised simply using jitpack not working, I also need to upgrade gradle version and SDK Android version.
